debug: true

detect_color: 0
binary_thres: 80

light:
  - min_ratio: 0.1
  - max_ratio: 0.4
  - max_angle: 40.0

armor:
 - min_light_ratio: 0.7
 - min_small_center_distance: 0.8
 - max_small_center_distance: 3.2
 - min_large_center_distance: 3.2
 - max_large_center_distance: 5.5
 - max_angle: 35.0

model_path: "/model/mlp.onnx"
label_path: "/model/label.txt"

classifier_threshold: 0.8
ignore_classes: ["negative"]

waitkey: 0
